### ISSUE TITLE
Visualization of features in your page

### ISSUE THREAD

**Issue by yangfeixia88** [Zhangjinso/PoNA#3]
Can you help me about  Visualization of features?
I can't find the relevant codes.
![image](https://user-images.githubusercontent.com/86911875/147059939-b2e59099-d067-497c-9191-9b3635ecd507.png)

**Comment by Zhangjinso** [comment]
You can refer to  [that](https://github.com/tengteng95/Pose-Transfer/issues/59#issuecomment-569392649).
